micronaut:
  application:
    name: fretes
  server:
    port: 8081

grpc:
  server:
    health:
      enabled: true # true por padrão

endpoints:
  all:
    port: 8085
    sensitive: true
  health:
    enabled: true # true por padrão
    sensitive: false
    details-visible: ANONYMOUS